spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
    enabled: true
server:
  port: 8181

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: beans
  endpoint:
    health:
      show-details: always
      env:
        show-values: when_authorized
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [traceId=%X{traceId}, spanId=%X{spanId}]"
